export const REQUEST_SEARCH_USER_REPO: string = "REQUEST_SEARCH_USER_REPO";
export const SUCCEED_SEARCH_USER_REPO: string = "SUCCEED_SEARCH_USER_REPO";
export const FAIL_SEARCH_USER_REPO: string = "FAIL_SEARCH_USER_REPO";
